github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: pahud/gitpod-workspace
#   file: .gitpod.Dockerfile


vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==